CREATE TABLE user 
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nome VARCHAR(40) NOT NULL,
	cognome VARCHAR(40) NOT NULL,
	data_nascita DATE NOT NULL,
	email VARCHAR(40) NOT NULL,
	password VARCHAR(40) NOT NULL
);